name: Go Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: # Add permissions
      contents: read
      pull-requests: read
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        cache: true
        
    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Clear module cache # Add cache clearing
      run: go clean -modcache

    - name: Run linter
      uses: golangci/golangci-lint-action@v6.1.1
      with:
        version: latest
        args: --timeout=5m --out-format=colored-line-number
        skip-cache: true # Skip cache to avoid permission issues